package io.synthesized.sample.insurance.model;

import lombok.Data;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents an insurance agent.",
    example = "{\"agentId\": 1, \"firstName\": \"Jane\", \"lastName\": \"Smith\", \"email\": \"jane.smith@example.com\", \"phone\": \"9876543210\", \"region\": \"Northeast\", \"licenseNumber\": \"LIC-123456\"}"
)
public class Agent {
    @Schema(description = "Unique identifier for the agent. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long agentId;

    @Schema(description = "First name of the agent.", example = "Jane")
    private String firstName;

    @Schema(description = "Last name of the agent.", example = "Smith")
    private String lastName;

    @Schema(description = "Email address of the agent.", example = "jane.smith@example.com")
    private String email;

    @Schema(description = "Phone number of the agent.", example = "9876543210")
    private String phone;

    @Schema(description = "Region where the agent operates.", example = "Northeast")
    private String region;

    @Schema(description = "License number of the agent.", example = "LIC-123456")
    private String licenseNumber;
}
