package io.synthesized.sample.insurance.model;

import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents an insurance claim.",
    example = "{\"claimId\": 1, \"policyId\": 1, \"claimNumber\": \"CLM-12345\", \"claimType\": \"Accident\", \"claimStatus\": \"Pending\", \"filedDate\": \"2024-05-01\", \"incidentDate\": \"2024-04-28\", \"claimAmount\": 5000.00, \"settlementAmount\": 4500.00, \"description\": \"Vehicle collision on highway\"}"
)
public class Claim {
    @Schema(description = "Unique identifier for the claim. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long claimId;

    @Schema(description = "ID of the policy associated with the claim.", example = "1")
    private Long policyId;

    @Schema(description = "Claim number.", example = "CLM-12345")
    private String claimNumber;

    @Schema(description = "Type of the claim. Allowed values: Accident, Theft, Damage, Medical, Liability.", example = "Accident", allowableValues = {"Accident", "Theft", "Damage", "Medical", "Liability"})
    private String claimType;

    @Schema(description = "Status of the claim. Allowed values: Pending, Approved, Rejected, Processing, Settled.", example = "Pending", allowableValues = {"Pending", "Approved", "Rejected", "Processing", "Settled"})
    private String claimStatus;

    @Schema(description = "Date when the claim was filed.", example = "2024-05-01")
    private LocalDate filedDate;

    @Schema(description = "Date when the incident occurred.", example = "2024-04-28")
    private LocalDate incidentDate;

    @Schema(description = "Amount claimed.", example = "5000.00")
    private BigDecimal claimAmount;

    @Schema(description = "Settlement amount.", example = "4500.00")
    private BigDecimal settlementAmount;

    @Schema(description = "Description of the claim.", example = "Vehicle collision on highway")
    private String description;
}
