package io.synthesized.sample.insurance.model;

import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents an insurance policy.",
    example = "{\"policyId\": 1, \"policyholderId\": 1, \"policyNumber\": \"POL-12345\", \"policyType\": \"Auto\", \"status\": \"Active\", \"coverageAmount\": 50000.00, \"premiumAmount\": 1200.00, \"paymentFrequency\": \"Monthly\", \"coverageLevel\": \"Comprehensive\", \"startDate\": \"2024-01-01\", \"endDate\": \"2025-01-01\"}"
)
public class Policy {
    @Schema(description = "Unique identifier for the policy. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long policyId;

    @Schema(description = "ID of the policyholder who owns the policy.", example = "1")
    private Long policyholderId;

    @Schema(description = "First name of the policyholder.", example = "John", accessMode = Schema.AccessMode.READ_ONLY)
    private String policyholderFirstName;

    @Schema(description = "Last name of the policyholder.", example = "Doe", accessMode = Schema.AccessMode.READ_ONLY)
    private String policyholderLastName;

    @Schema(description = "Policy number.", example = "POL-12345")
    private String policyNumber;

    @Schema(description = "Type of the policy. Allowed values: Auto, Home, Life, Health, Business.", example = "Auto", allowableValues = {"Auto", "Home", "Life", "Health", "Business"})
    private String policyType;

    @Schema(description = "Status of the policy. Allowed values: InForce, Bound, Expired, Cancelled, Draft, Withdrawn.", example = "InForce", allowableValues = {"InForce", "Bound", "Expired", "Cancelled", "Draft", "Withdrawn"})
    private String status;

    @Schema(description = "Coverage amount of the policy.", example = "50000.00")
    private BigDecimal coverageAmount;

    @Schema(description = "Premium amount of the policy.", example = "1200.00")
    private BigDecimal premiumAmount;

    @Schema(description = "Payment frequency. Allowed values: Monthly, Quarterly, SemiAnnually, Annually.", example = "Monthly", allowableValues = {"Monthly", "Quarterly", "SemiAnnually", "Annually"})
    private String paymentFrequency;

    @Schema(description = "Coverage level. Allowed values: Basic, Standard, Comprehensive, Premium.", example = "Comprehensive", allowableValues = {"Basic", "Standard", "Comprehensive", "Premium"})
    private String coverageLevel;

    @Schema(description = "Start date of the policy.", example = "2024-01-01")
    private LocalDate startDate;

    @Schema(description = "End date of the policy.", example = "2025-01-01")
    private LocalDate endDate;

    @Schema(description = "Number of claims associated with this policy.", example = "3", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer claimCount;
}
