package io.synthesized.sample.insurance.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(
    description = "Represents an insurance policyholder.",
    example = "{\"policyholderId\": 1, \"firstName\": \"John\", \"lastName\": \"Doe\", \"email\": \"john@example.com\", \"phone\": \"1234567890\", \"dateOfBirth\": \"1980-01-15\", \"policyholderType\": \"Individual\", \"createdAt\": \"2024-05-01T12:00:00\", \"policyIds\": [101, 102]}"
)
public class Policyholder {
    @Schema(description = "Unique identifier for the policyholder. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long policyholderId;

    @Schema(description = "First name of the policyholder.", example = "John")
    private String firstName;

    @Schema(description = "Last name of the policyholder.", example = "Doe")
    private String lastName;

    @Schema(description = "Email address of the policyholder.", example = "john@example.com")
    private String email;

    @Schema(description = "Phone number of the policyholder.", example = "1234567890")
    private String phone;

    @Schema(description = "Date of birth of the policyholder.", example = "1980-01-15")
    private LocalDate dateOfBirth;

    @Schema(description = "Type of the policyholder. Allowed values: Individual, Business, Family, Group.", example = "Individual", allowableValues = {"Individual", "Business", "Family", "Group"})
    private String policyholderType;

    @Schema(description = "Timestamp when the policyholder was created.", example = "2024-05-01T12:00:00")
    private LocalDateTime createdAt;

    @Schema(description = "List of policy IDs associated with the policyholder.", example = "[101, 102]")
    private List<Long> policyIds;

    // Getters and Setters
    public Long getPolicyholderId() {
        return policyholderId;
    }

    public void setPolicyholderId(Long policyholderId) {
        this.policyholderId = policyholderId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getPolicyholderType() {
        return policyholderType;
    }

    public void setPolicyholderType(String policyholderType) {
        this.policyholderType = policyholderType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public List<Long> getPolicyIds() {
        return policyIds;
    }

    public void setPolicyIds(List<Long> policyIds) {
        this.policyIds = policyIds;
    }
}
