package io.synthesized.sample.bank.model;

import lombok.Data;
import java.math.BigDecimal;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents a bank account.",
    example = "{\"accountId\": 1, \"customerId\": 1, \"accountType\": \"Checking\", \"status\": \"Active\", \"balance\": 1000.00}"
)
public class Account {
    @Schema(description = "Unique identifier for the account. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer accountId;

    @Schema(description = "ID of the customer who owns the account.", example = "1")
    private Integer customerId;

    @Schema(description = "Type of the account. Allowed values: Checking, Savings, Credit, Loan, Investment.", example = "Checking", allowableValues = {"Checking", "Savings", "Credit", "Loan", "Investment"})
    private String accountType;

    @Schema(description = "Status of the account. Allowed values: Active, Closed, Frozen, Dormant, Overdrawn.", example = "Active", allowableValues = {"Active", "Closed", "Frozen", "Dormant", "Overdrawn"})
    private String status;

    @Schema(description = "Current balance of the account.", example = "1000.00")
    private BigDecimal balance;
} 