package io.synthesized.sample.bank.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(
    description = "Represents a bank branch.",
    example = "{\"branch_id\": 1, \"name\": \"Main Street\", \"region\": \"North\", \"manager_name\": \"Alice Band\"}"
)
public class Branch {
    @JsonProperty("branch_id")
    @Schema(
        description = "Unique identifier for the branch. Auto-generated by the system.",
        example = "1",
        accessMode = Schema.AccessMode.READ_ONLY
    )
    private Integer branchId;
    
    @Schema(
        description = "Name of the branch.",
        example = "Main Street"
    )
    private String name;
    
    @Schema(
        description = "Region of the branch. Allowed values: North, South, East, West, Central.",
        example = "North",
        allowableValues = {"North", "South", "East", "West", "Central"}
    )
    private String region;
    
    @JsonProperty("manager_name")
    @Schema(
        description = "Name of the branch manager.",
        example = "Alice Band"
    )
    private String managerName;
} 