package io.synthesized.sample.bank.model;

import java.time.LocalDateTime;
import java.util.List;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(
    description = "Represents a bank customer.",
    example = "{\"customerId\": 1, \"firstName\": \"John\", \"lastName\": \"Doe\", \"email\": \"john@example.com\", \"phone\": \"1234567890\", \"customerType\": \"Individual\", \"createdAt\": \"2024-05-01T12:00:00\", \"accountIds\": [101, 102]}"
)
public class Customer {
    @Schema(description = "Unique identifier for the customer. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long customerId;

    @Schema(description = "First name of the customer.", example = "John")
    private String firstName;

    @Schema(description = "Last name of the customer.", example = "Doe")
    private String lastName;

    @Schema(description = "Email address of the customer.", example = "john@example.com")
    private String email;

    @Schema(description = "Phone number of the customer.", example = "1234567890")
    private String phone;

    @Schema(description = "Type of the customer. Allowed values: Individual, Business, VIP, Government, Nonprofit.", example = "Individual", allowableValues = {"Individual", "Business", "VIP", "Government", "Nonprofit"})
    private String customerType;

    @Schema(description = "Timestamp when the customer was created.", example = "2024-05-01T12:00:00")
    private LocalDateTime createdAt;

    @Schema(description = "List of account IDs associated with the customer.", example = "[101, 102]")
    private List<Long> accountIds;

    // Getters and Setters
    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCustomerType() {
        return customerType;
    }

    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public List<Long> getAccountIds() {
        return accountIds;
    }

    public void setAccountIds(List<Long> accountIds) {
        this.accountIds = accountIds;
    }
} 