package io.synthesized.sample.bank.model;

import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents a bank transaction.",
    example = "{\"transactionId\": 1, \"accountId\": 1, \"transactionType\": \"Deposit\", \"transactionDate\": \"2024-05-01T12:00:00\", \"amount\": 100.00, \"channel\": \"ATM\", \"currency\": \"USD\", \"channelDetails\": \"ATM #123\", \"location\": \"New York\", \"deviceType\": \"Desktop\", \"authMethod\": \"Password\"}"
)
public class Transaction {
    @Schema(description = "Unique identifier for the transaction. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Integer transactionId;

    @Schema(description = "ID of the account associated with the transaction.", example = "1")
    private Integer accountId;

    @Schema(description = "Type of the transaction. Allowed values: Deposit, Withdrawal, Transfer, Payment, Fee.", example = "Deposit", allowableValues = {"Deposit", "Withdrawal", "Transfer", "Payment", "Fee"})
    private String transactionType;

    @Schema(description = "Date and time when the transaction occurred.", example = "2024-05-01T12:00:00")
    private LocalDateTime transactionDate;

    @Schema(description = "Amount of the transaction.", example = "100.00")
    private BigDecimal amount;

    @Schema(description = "Channel through which the transaction was made. Allowed values: Online, ATM, Branch, Mobile, Wire.", example = "ATM", allowableValues = {"Online", "ATM", "Branch", "Mobile", "Wire"})
    private String channel;

    @Schema(description = "Currency of the transaction. Allowed values: USD, EUR, GBP, JPY, AUD.", example = "USD", allowableValues = {"USD", "EUR", "GBP", "JPY", "AUD"})
    private String currency;

    @Schema(description = "Additional details about the channel.", example = "ATM #123")
    private String channelDetails;

    @Schema(description = "Location where the transaction occurred.", example = "New York")
    private String location;

    @Schema(description = "Type of device used for the transaction. Allowed values: Desktop, Mobile, Tablet, Kiosk, ATM.", example = "Desktop", allowableValues = {"Desktop", "Mobile", "Tablet", "Kiosk", "ATM"})
    private String deviceType;

    @Schema(description = "Authentication method used. Allowed values: Password, 2FA, Biometric, PIN, Card.", example = "Password", allowableValues = {"Password", "2FA", "Biometric", "PIN", "Card"})
    private String authMethod;
} 