package io.synthesized.sample.healthcare.model;

import lombok.Data;
import java.time.LocalDateTime;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents a healthcare appointment.",
    example = "{\"appointmentId\": 1, \"patientId\": 1, \"providerName\": \"Dr. Smith\", \"appointmentType\": \"Checkup\", \"status\": \"Scheduled\", \"appointmentDate\": \"2024-05-15T10:00:00\", \"duration\": 30, \"department\": \"GeneralPractice\"}"
)
public class Appointment {
    @Schema(description = "Unique identifier for the appointment. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long appointmentId;

    @Schema(description = "ID of the patient for the appointment.", example = "1")
    private Long patientId;

    @Schema(description = "First name of the patient.", example = "John", accessMode = Schema.AccessMode.READ_ONLY)
    private String patientFirstName;

    @Schema(description = "Last name of the patient.", example = "Doe", accessMode = Schema.AccessMode.READ_ONLY)
    private String patientLastName;

    @Schema(description = "ID of the provider for the appointment.", example = "1")
    private Long providerId;

    @Schema(description = "Name of the provider for the appointment.", example = "Dr. Smith")
    private String providerName;

    @Schema(description = "Type of the appointment. Allowed values: Consultation, FollowUp, Emergency, Surgery, Checkup, Vaccination.", example = "Checkup", allowableValues = {"Consultation", "FollowUp", "Emergency", "Surgery", "Checkup", "Vaccination"})
    private String appointmentType;

    @Schema(description = "Status of the appointment. Allowed values: Scheduled, Confirmed, InProgress, Completed, Cancelled, NoShow.", example = "Scheduled", allowableValues = {"Scheduled", "Confirmed", "InProgress", "Completed", "Cancelled", "NoShow"})
    private String status;

    @Schema(description = "Date and time of the appointment.", example = "2024-05-15T10:00:00")
    private LocalDateTime appointmentDate;

    @Schema(description = "Duration of the appointment in minutes.", example = "30")
    private Integer duration;

    @Schema(description = "Department for the appointment.", example = "GeneralPractice", allowableValues = {"Cardiology", "Neurology", "Pediatrics", "Orthopedics", "Dermatology", "Emergency", "GeneralPractice"})
    private String department;
}
