package io.synthesized.sample.healthcare.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(
    description = "Represents a healthcare patient.",
    example = "{\"patientId\": 1, \"firstName\": \"John\", \"lastName\": \"Doe\", \"email\": \"john@example.com\", \"phone\": \"1234567890\", \"dateOfBirth\": \"1980-01-15\", \"bloodType\": \"A+\", \"createdAt\": \"2024-05-01T12:00:00\", \"appointmentIds\": [101, 102]}"
)
public class Patient {
    @Schema(description = "Unique identifier for the patient. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long patientId;

    @Schema(description = "First name of the patient.", example = "John")
    private String firstName;

    @Schema(description = "Last name of the patient.", example = "Doe")
    private String lastName;

    @Schema(description = "Email address of the patient.", example = "john@example.com")
    private String email;

    @Schema(description = "Phone number of the patient.", example = "1234567890")
    private String phone;

    @Schema(description = "Date of birth of the patient.", example = "1980-01-15")
    private LocalDate dateOfBirth;

    @Schema(description = "Blood type of the patient. Allowed values: A+, A-, B+, B-, AB+, AB-, O+, O-.", example = "A+", allowableValues = {"A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"})
    private String bloodType;

    @Schema(description = "Timestamp when the patient was created.", example = "2024-05-01T12:00:00")
    private LocalDateTime createdAt;

    @Schema(description = "List of appointment IDs associated with the patient.", example = "[101, 102]")
    private List<Long> appointmentIds;

    @Schema(description = "Medical record number of the patient.", example = "MRN-2024-001")
    private String medicalRecordNumber;

    @Schema(description = "Patient type. Allowed values: Adult, Pediatric, Geriatric, Prenatal, Emergency.", example = "Adult", allowableValues = {"Adult", "Pediatric", "Geriatric", "Prenatal", "Emergency"})
    private String patientType;

    @Schema(description = "Insurance policy ID linked to this patient for cross-system integration.", example = "1")
    private Long insurancePolicyId;

    // Getters and Setters
    public Long getPatientId() {
        return patientId;
    }

    public void setPatientId(Long patientId) {
        this.patientId = patientId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getBloodType() {
        return bloodType;
    }

    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public List<Long> getAppointmentIds() {
        return appointmentIds;
    }

    public void setAppointmentIds(List<Long> appointmentIds) {
        this.appointmentIds = appointmentIds;
    }

    public String getMedicalRecordNumber() {
        return medicalRecordNumber;
    }

    public void setMedicalRecordNumber(String medicalRecordNumber) {
        this.medicalRecordNumber = medicalRecordNumber;
    }

    public String getPatientType() {
        return patientType;
    }

    public void setPatientType(String patientType) {
        this.patientType = patientType;
    }

    public Long getInsurancePolicyId() {
        return insurancePolicyId;
    }

    public void setInsurancePolicyId(Long insurancePolicyId) {
        this.insurancePolicyId = insurancePolicyId;
    }
}
