package io.synthesized.sample.healthcare.model;

import lombok.Data;
import java.time.LocalDate;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents a medical prescription.",
    example = "{\"prescriptionId\": 1, \"appointmentId\": 1, \"patientId\": 1, \"providerId\": 1, \"medicationName\": \"Amoxicillin\", \"dosage\": \"500mg\", \"frequency\": \"Twice daily\", \"startDate\": \"2024-05-01\", \"endDate\": \"2024-05-15\", \"instructions\": \"Take with food\"}"
)
public class Prescription {
    @Schema(description = "Unique identifier for the prescription. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long prescriptionId;

    @Schema(description = "ID of the appointment associated with the prescription.", example = "1")
    private Long appointmentId;

    @Schema(description = "ID of the patient who the prescription is for.", example = "1")
    private Long patientId;

    @Schema(description = "ID of the provider who prescribed the medication.", example = "1")
    private Long providerId;

    @Schema(description = "Name of the medication.", example = "Amoxicillin")
    private String medicationName;

    @Schema(description = "Dosage of the medication.", example = "500mg")
    private String dosage;

    @Schema(description = "Frequency of medication. Allowed values: Once daily, Twice daily, Three times daily, Four times daily, As needed.", example = "Twice daily", allowableValues = {"Once daily", "Twice daily", "Three times daily", "Four times daily", "As needed"})
    private String frequency;

    @Schema(description = "Start date of the prescription.", example = "2024-05-01")
    private LocalDate startDate;

    @Schema(description = "End date of the prescription.", example = "2024-05-15")
    private LocalDate endDate;

    @Schema(description = "Instructions for taking the medication.", example = "Take with food")
    private String instructions;
}
