package io.synthesized.sample.healthcare.model;

import lombok.Data;
import io.swagger.v3.oas.annotations.media.Schema;

@Data
@Schema(
    description = "Represents a healthcare provider.",
    example = "{\"providerId\": 1, \"firstName\": \"Jane\", \"lastName\": \"Smith\", \"email\": \"jane.smith@example.com\", \"phone\": \"9876543210\", \"specialty\": \"Cardiology\", \"licenseNumber\": \"LIC-123456\"}"
)
public class Provider {
    @Schema(description = "Unique identifier for the provider. Auto-generated by the system.", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long providerId;

    @Schema(description = "First name of the provider.", example = "Jane")
    private String firstName;

    @Schema(description = "Last name of the provider.", example = "Smith")
    private String lastName;

    @Schema(description = "Email address of the provider.", example = "jane.smith@example.com")
    private String email;

    @Schema(description = "Phone number of the provider.", example = "9876543210")
    private String phone;

    @Schema(description = "Medical specialty of the provider. Allowed values: Cardiology, Dermatology, Neurology, Pediatrics, Orthopedics.", example = "Cardiology", allowableValues = {"Cardiology", "Dermatology", "Neurology", "Pediatrics", "Orthopedics"})
    private String specialty;

    @Schema(description = "License number of the provider.", example = "LIC-123456")
    private String licenseNumber;
}
