apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bank-database-credentials
  labels:
    {{- include "bank-demo.labels" . | nindent 4 }}
spec:
  refreshInterval: "0s"
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{ .Values.database.usernameKey }}: "{{ `{{ index . \"username\" }}` }}"
        {{ .Values.database.passwordKey }}: "{{ `{{ index . \"password\" }}` }}"
        jdbc-url-seed: "jdbc:postgresql://{{ include "bank-demo.connectionHost" . }}:{{ .Values.dbExposure.port }}/{{ .Values.database.names.seed }}?sslmode=require"
        jdbc-url-small: "jdbc:postgresql://{{ include "bank-demo.connectionHost" . }}:{{ .Values.dbExposure.port }}/{{ .Values.database.names.seed }}?sslmode=require"
        jdbc-url-prod: "jdbc:postgresql://{{ include "bank-demo.connectionHost" . }}:{{ .Values.dbExposure.port }}/{{ .Values.database.names.prod }}?sslmode=require"
        jdbc-url-testing: "jdbc:postgresql://{{ include "bank-demo.connectionHost" . }}:{{ .Values.dbExposure.port }}/{{ .Values.database.names.testing }}?sslmode=require"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: bank-database-username
      rewrite:
        - regexp:
            source: "^password$"
            target: "username"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: bank-database-password
      rewrite:
        - regexp:
            source: "^password$"
            target: "password"
