apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: bank-database-username
spec:
  length: 16
  digits: 2
  symbols: 0
  noUpper: true
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: bank-database-password
spec:
  length: 32
  digits: 4
  symbols: 0
  allowRepeat: true
